require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BookmarksController do
  render_views

  # This should return the minimal set of attributes required to create a valid
  # Bookmark. As you add validations to Bookmark, be sure to
  # update the return value of this method accordingly.

  before(:each) do
        @base_title = "Juicee!"
  end

  #def valid_attributes
  #    {
  #              :url => "www.yahoo.com",
  #              :name => "yahoo.com"
  #    }
  #end



  describe "access control" do

    it "should deny access to 'create'" do
      post :create
      response.should redirect_to(signin_path)
    end

    it "should deny access to 'bookmarks index'" do
        get :index
      response.should redirect_to(signin_path)
    end

    it "should deny access to 'destroy'" do
      delete :destroy, :id => 1
      response.should redirect_to(signin_path)
    end
  end

  describe "GET 'index'" do
      before(:each) do
          @user = test_sign_in(Factory(:user))
      end

      it "should be successful" do
          get :index, :id => @user
        response.should be_success
      end

      it "should show the user's bookmarks" do
        mp1 = Factory(:bookmark, :user => @user, :url => "www.yahoo.com")
        mp2 = Factory(:bookmark, :user => @user, :url => "www.google.com")
        get :index, :id => @user
        response.should have_selector("span.url", :content => mp1.url)
        response.should have_selector("span.url", :content => mp2.url)
      end
  end

  describe "GET show" do
    before(:each) do
            @bookmark = Factory(:bookmark)
    end

    it "should be successful" do
      get :show, :id => @bookmark
      response.should be_success
    end
  end


  describe "POST 'create'" do

    before(:each) do
        @user = test_sign_in(Factory(:user))
    end

    describe "failure" do

      before(:each) do
        @attr = { :url => "",
                :name => "" }
      end

      it "should not create a bookmark" do
        lambda do
          post :create, :bookmark => @attr
        end.should_not change(Bookmark, :count)
      end

      it "should render the home page" do
        post :create, :bookmark => @attr
        response.should render_template('new')
      end
    end

    describe "success" do

      before(:each) do
        @attr = { :url => "www.yahoo.com",
                :name => "yahoo.com" }
      end

      it "should create a bookmark" do
        lambda do
          post :create, :bookmark => @attr
        end.should change(Bookmark, :count).by(1)
      end

      it "should redirect to the home page" do
        post :create, :bookmark => @attr
        response.should redirect_to(bookmark_path(assigns(:bookmark)))
      end

      it "should have a flash message" do
        post :create, :bookmark => @attr
        flash[:success].should =~ /bookmark created/i
      end
    end
  end

  describe "DELETE 'destroy'" do

    describe "for an unauthorized user" do

      before(:each) do
        @user = Factory(:user)
        wrong_user = Factory(:user, :user_name => "user#{rand(1000).to_s}",
            :email => "email#{rand(1000).to_s}@soco.org")
        test_sign_in(wrong_user)
        @bookmark = Factory(:bookmark, :user => @user)
      end

      it "should deny access" do
        delete :destroy, :id => @bookmark
        response.should redirect_to(root_path)
      end
    end

    describe "for an authorized user" do

      before(:each) do
        @user = test_sign_in(Factory(:user))
        @bookmark = Factory(:bookmark, :user => @user)
      end

      it "should destroy the bookmark" do
        lambda do
          delete :destroy, :id => @bookmark
        end.should change(Bookmark, :count).by(-1)
      end
    end
  end

end

